### ISSUE TITLE
platform literal

### ISSUE THREAD

**Issue by medhatelmasry** [plan-your-vote/plan-your-vote-cda#87]
The front-end is specifically looking for platform info. If the word platform is changed to platform1 on the backend, it does not get pulled (Ask Ryan)

**Comment by ryanliang88** [comment]
I believe the reason why it cannot be changed to Platform1 as you may expect it is because the `List<CandidateDetail>` on a `Candidate`  holds its candidate details and the property `Title` on `CandidateDetail` essentially stores the string "Platform" which is data in `candidates.json`.
Might be referring to:
Web\Models\CandidateDetail.cs Line 40
Web\wwwroot\data\candidates.json Line 10

I also believe this is because the front-end is currently hard coded to know that Platform data is being served from the back-end. 
Might be referring to:
src\components\CandidateModal\index.jsx Line 170

This is currently how Candidates can have any data and know how to display itself (via Candidate DetailFormat; I believe how it displays itself is unimplemented and hard coded). The front-end should dynamically serve all data it receives and either the front-end should know how that data should be displayed or that data should know how to display itself.

Aside: JSONCandidate's Platform property has little to do with this issue and only serves as a way to seed data.

**Comment by medhatelmasry** [comment]
Fixed by team Amanda Golubics de Andrade, Darren	Wang, Younhee Lee as part of assignment 2
